# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f69f4eaf3bb7e7f89677fd08e20697eb7ac2873dcec4ee7012b5a4e9810ef439dcf1c3d56fc379ab9e96274306f24fdd9d71561b0916fe9e5e63ec0ea4bb50d6

test:
  secret_key_base: cd3c95ea72736e36f7221531d8ea310ed6d780e55b909838b70821a2ac5e29e98436e44c51d7c009a2bfd3f311ab4626b2afe9db77effc8b545543563ef8f78a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
